favicon: null
name: Graphic.Ref
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.325188
  brandStrength: 0.2418784038163722
  lightness: 0.1190476
  brandColors:
    - '#f1f5f8'
    - '#a19e99'
    - '#101008'
    - '#4c433a'
    - '#776e67'
  rhythmicContrast: 0.4661654
typography_spectrum: 0.9110276
layout_spectrum: 0.7681704
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
