name: Graphic.Ref
favicon: null
layout_spectrum: 0.8221855545416474
typography_spectrum: 0.5966274270322174
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f1f5f8'
    - '#a19e99'
    - '#101008'
    - '#4c433a'
    - '#776e67'
  brandStrength: 0.24187840381637216
  lightness: 0.8032527465838939
  saturation: 0.6338545482140034
  rhythmicContrast: 0.5667932333890349
purpose: []
